version: '3.8'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=notebook