# Generated by Django 4.1.4 on 2022-12-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id_uniq', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор документа')),
                ('title', models.CharField(max_length=25, verbose_name='Document_name')),
                ('document', models.FileField(upload_to='uploads/pdf', verbose_name='Document_file')),
                ('interpretation_html', models.FileField(null=True, upload_to='uploads/html', verbose_name='Document_html')),
                ('interpretation_json', models.FileField(null=True, upload_to='uploads/json', verbose_name='Document_html')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
